### ISSUE TITLE
To many permissions required to Copy Database Views

### ISSUE THREAD

**Issue by conyg** [webyog/sqlyog-community#2086]
I have a READ ONLY user setup on my Source host having the following permissions:
 - SELECT, LOCK TABLES and SHOW VIEW on **demo** database
 - SELECT on mysql database

Please note that these permissions are enough to export **demo** database from sqlyog.

For the same user the **copy database to a different host** fails to copy **views**.
Statement: `CREATE TEMPORARY TABLE 'demo'.'contract_last_doc' SELECT * FROM 'demo'.'contract_last_doc' WHERE 0`
Error: `Access denied for user 'myuser'@'xx.xx.xx.xxx' to database 'demo'`.

For some reason user needs to create a temporary table on the source host to copy a view. I assigned  CREATE TEMPORARY TABLES permissions to the user but the copy fails again at the same statement with the error: `INSERT command denied to user 'myuser'@'xx.xx.xx.xxx'  for table 'contract_last_doc'`
I don't think is necessary to give INSERT permissions to copy views. As long as user can export the views using the export command he must be able to copy views with the same permissions

**Comment by Kartikwy** [comment]
-- Please reply above this line --



I have a READ ONLY user setup on my Source host having the following
permissions:

	* SELECT, LOCK TABLES and SHOW VIEW on demo database
	* SELECT on mysql database Please note that these permissions are
enough to export demo database from sqlyog.

For the same user the COPY DATABASE TO A DIFFERENT HOST fails to copy
VIEWS.

Statement: CREATE TEMPORARY TABLE 'demo'.'contract_last_doc' SELECT *
FROM 'demo'.'contract_last_doc' WHERE 0
Error: Access denied for user 'myuser'@'xx.xx.xx.xxx' to database
'demo'.
For some reason user needs to create a temporary table on the source
host to copy a view. I assigned CREATE TEMPORARY TABLES permissions to
the user but the copy fails again at the same statement with the
error: INSERT command denied to user 'myuser'@'xx.xx.xx.xxx' for table
'contract_last_doc'
I don't think is necessary to give INSERT permissions to copy views.
As long as user can export the views using the export command he must
be able to copy views with the same permissions

**Comment by Kartikwy** [comment]
-- Please reply above this line --


Please tell your MySQl version. Privileges when copying a VIEW for
MySQl 5.6 are liited in MySQL documentation here:
https://dev.mysql.com/doc/refman/5.6/en/create-view.html [1]. There
may be differences with older versions. 

"For some reason user needs to create a temporary table on the source
host to copy a view". Yes, because this is the only safe way ot handle
'views built on views'.

We will check this.

Links:
------
[1] https://dev.mysql.com/doc/refman/5.6/en/create-view.html

**Comment by Kartikwy** [comment]
-- Please reply above this line --


For us it works with CREATE TEMPORARY TABLES privilege and MySQL
5.6.22. Details:

Successful in the case when the Grants for test_view@% were: 
----------------------------------------------------------------------------------------------------------
GRANT USAGE ON *.* TO 'test_view'@'%' IDENTIFIED BY PASSWORD
'*94BDCEBE19083CE2A1F959FD02F964C7AF4CFC29' 
GRANT SELECT, CREATE TEMPORARY TABLES, LOCK TABLES, SHOW VIEW ON
`sakila`.* TO 'test_view'@'%' 

Unsuccessful in the case when the Grants were:
----------------------------------------------------------------------------------------------------------
GRANT USAGE ON *.* TO 'test_view'@'%' IDENTIFIED BY PASSWORD
'*94BDCEBE19083CE2A1F959FD02F964C7AF4CFC29' 
GRANT SELECT, LOCK TABLES, SHOW VIEW ON `sakila`.* TO 'test_view'@'%' 

One request: could you please reply to this mail, so that we can see
that you are getting and reading mails from us. We will not use the
issue tracker for discusions with users, but our mail-based support
system.

**Comment by conyg** [comment]
We have mysql server version 5.5.44 on linux debian.
Unfortunately on this version of mysql, sqlyog  requires also insert
permissions.
