### ISSUE TITLE
Warning Virus?

### ISSUE THREAD

**Issue by LdyMox** [webyog/sqlyog-community#2110]
Warning; While it could be a false postive, Kasperky End Point Security 10 detected a vrius in SQLyog Community Edition - 12.2.2 (32-Bit) upon attempted install (Trojan.Win32.Generic)

**Comment by peterwy** [comment]
It is a false positive.

We have had such false positives with almost any AV software I can think of over the 1++ years I have been here. It usually gets resolved in a fe days with new signatrues from the AV vendor (most modern AV software will communicate back to the vendor what they find and do). 

You can:
1) ensure that your AV software is always kept updated with latest signatures.
2) turn off the AV temporarily while downloading and installing. It is probably the installer and not the program_as_such (ie. program binary) that causes the AV to raise this alert. if so the AV will not complain once the program is installed

I am closing this.  You are welcome to contact us at support@webyog.com if you want. It is a better option than here. This place is an *issuetracker for SQLyog* and the problem is not a issue with SQLyog but with specific AV signatures from Kaspersky. We cannot do anything about it (contacting the AV vendor leads nowhere (we have tried) but none of them ever replied)  If you are a paying customer (and best of all a corporate customer) there are better chances that they will reply to you than to us. 

But thanks for informing us anyway!

**Comment by LdyMox** [comment]
Thanks for the quick reponse, my AV is up to date but I know false postives do happen. :)
