### ISSUE TITLE
'default' string in varchar column replaced with DEFAULT value from the column definition

### ISSUE THREAD

**Issue by humeniuc** [webyog/sqlyog-community#2129]
When I update a table field of varchar type (from the "Table data" tab) with the string '**default**', the field is updated with de DEFAULT value from the column definition instead.

steps:
CREATE TABLE `tbl` (                                                                              
          `txt` varchar(255) DEFAULT 'def_val'                                                            
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8  

1. I select the "Table data" tab for the table. I insert '**lorem ipsum**' in the txt field.
2. check History tab, the query executed was
INSERT INTO `test`.`tbl` (`txt`) VALUES ('**lorem ipsum**'); 
3. I edit the field, and replace '**lorem ipsum**' with '**default**'.
4. check History tab, the query executed was
UPDATE `test`.`tbl` SET `txt` = '**def_val**' WHERE `txt` = '**lorem ipsum'**;

**Comment by humeniuc** [comment]
Just checked the options and found a default checked option for this  behavior.

**Comment by peterwy** [comment]
This is intentional.  Please refer this FAQ: http://faq.webyog.com/8_99_en.html

And it is in accordance with MySQL syntax for INSERT and UPDATE.  Refer for instance http://dev.mysql.com/doc/refman/5.7/en/update.html
" ... SET col_name1={expr1|**DEFAULT**} ..."
"default" (without quotes) is a column specifier in MySQL. Not an expression nor a (string) value.

Turn "snart keywords" off in preferences or use backticks as the FAQ describes it.
