### ISSUE TITLE
Feature request - Elements count

### ISSUE THREAD

**Issue by gnovaro** [webyog/sqlyog-community#2219]
Add element count inside tree view, like HeidiSQL is realy usefull, in a single view you can see is have a difference between 2 diferent enviroments. 
![feature_elements_count](https://user-images.githubusercontent.com/270990/58186306-e9347f00-7cb4-11e9-927c-b5837db846dc.png)

**Comment by gnovaro** [comment]
SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = "apcapi"

**Comment by sibwy** [comment]
We already have this feature in SQLyog, but we use a different approach. Please follow the steps below to view the count,

1) Select the database int he Object browser (the left-pane that lists the databases in the server)
2) Click on the 'Info' tab in the 'Result Window'

<img width="678" alt="Object count" src="https://user-images.githubusercontent.com/15195164/58235795-29e8d280-7d5f-11e9-9556-e90781ae5121.png">

For further queries/suggestions, please contact us on email at [ideramysqlsupport@idera.com](mailto: ideramysqlsupport@idera.com). The way we use GitHub is strictly as an issue-tracker for known issues and not for support or discussions. This is necessary in order to keep the system manageable.

**Comment by gnovaro** [comment]
Thanks for the feeback
