### ISSUE TITLE
Data is duplicated in target table using 'Copy Database to Different Host/Database'

### ISSUE THREAD

**Issue by sibwy** [webyog/sqlyog-community#2223]
The data from the source table is copied to the target in an infinite loop using the 'Copy Database to Different Host/Database" on setting the 'Chunk size' value to "0" under 'Tools -> Preferences -> General' tab.

The user report can be found in SF >> 00704844

**Comment by peterwy** [comment]
maybe we should simply refuse to close the dialog in such case with an error message like "chunk size must be a positive integer" or similar.

**Comment by alfaguru** [comment]
Hi, I am the user who reported this bug. I don't think a fix at the dialog level is enough because as far as I know I never set the size to 0, I think it got set from a previous install. I would always advocate sanity checking at run time because config files can get corrupted or amended in unpredictable ways.

**Comment by sibwy** [comment]
Fixed in [v13.1.7](https://blog.sqlyog.com/sqlyog-mysql-gui-13-1-7-released/)
