### ISSUE TITLE
Repository documentation

### ISSUE THREAD

**Issue by gnovaro** [webyog/sqlyog-community#2241]
We need more information about the project:
- Compiling instruction, requirements, libraries
- Add description to the project repository
- Add tags to project repository

**Comment by gnovaro** [comment]
Why close?

**Comment by sibwy** [comment]
Your questions do not seem to be related to a problem/issue concerned with SQLyog product. Therefore, please contact us on email at [ideramysqlsupport@idera.com](ideramysqlsupport@idera.com) about this. 

The way we use GitHub is strictly as an issue-tracker for known issues and not for support or discussions. This is necessary in order to keep the system manageable.

**Comment by gnovaro** [comment]
That is not the idea of open source.

**Comment by illfated** [comment]
> That is not the idea of open source.

I beg to differ. Unless the actual documentation is open source as well, (like Microsoft Docs), requests like this belong to the forum pages or support, not the software issue tracker.
