### ISSUE TITLE
Disable Upgrade Prompt On Exit?

### ISSUE THREAD

**Issue by WebSpectrum** [webyog/sqlyog-community#2242]
Is it not possible to disable the upgrade window/prompt on exit?

**Comment by illfated** [comment]
Not very likely, unless you download the source and manipulate it yourself.

To my mind, that type of change goes against the purpose of advertising the full version. Remember, the owners and sales department in the company Webyog do want to sell their product, which is the full version. The fact that they provide a community version for free is more than enough for me, because it is part of the deal that the free version advertises the full version without these reminders.

Short answer: No, at least not in any simple way. If you want to get rid of the non-work-related messages, buy the full version.
(BTW, some of the reminders in the community version openly tell you that all features are available in the full version.)
