### ISSUE TITLE
Database name with hyphens needs escaping

### ISSUE THREAD

**Issue by larsen0815** [webyog/sqlyog-community#2251]
I got this error with SQLyog 13.1.6 when trying to open "Table Data" from `test-fail.mytable`:
````
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-fail.mytable
 limit 0, 1000' at line 1
````

Database name (and probably table name) needs escaping with backticks.
MariaDB 10.1

**Comment by illfated** [comment]
When I started learning to use SQL/MySQL, I learned to use back ticks around column names, table names and DB names all the time. The way I understood it, it was only allowed to let SQL keywords be without back ticks or quotes. I suppose I have escaped a lot of rabbit holes that way.

**Comment by sibwy** [comment]
This is not a bug. You are getting this error because you have unchecked the checkbox "Generate queries using backquote(`)" in the 'General' tab under the menu "Tools -> Preferences".

This option is checked by default. You may also click on the 'Restore Tab Defaults' button at the bottom or check the above-mentioned checkbox.

**Comment by larsen0815** [comment]
Thanks!
Why is this configurable if it leads to erroneous behaviour?

**Comment by sibwy** [comment]
A lot of people find the backquotes *ugly*, and some people also find that backquotes make scripts less readable. The preferences option to enable/dismiss those is actually an implementation of a user request from many years ago.

Besides the default setting is to generate backquotes.
