### ISSUE TITLE
"Copy table..." disabled with read only user

### ISSUE THREAD

**Issue by mclaborn** [webyog/sqlyog-community#2266]
SQLyog 13.1.7
mysql 8.0.21

I have a read-only user (only global privileges: Execute, Select, Show View) that I use most of the time in SQLyog.  With that user, the "Copy Table(s) to Different Host/Database..." right click entry is disabled. What privilege is missing to make that work? It works fine with a fully privileged user.

**Comment by illfated** [comment]
Even though I am not part of the SQLyog team or affiliated in any way (not even an advanced user of SQLyog), I would like to comment based on my previous experiences with GitHub tickets in general.

From what I can tell based on my personal experience, it is usually preferred to post questions in the forum pages instead of a ticket here in this repository. You may want to wait for a reply from the webyog team to see what they recommend doing in your case.

**Comment by sibwy** [comment]
Please refer to the KB for the statements that are allowed in 'Read-Only' mode, [here](https://sqlyogkb.webyog.com/article/29-sqlyog-in-read-only-mode).

**Comment by mclaborn** [comment]
What confused me was the I had the read-only flag set on the database that was to be the source of a table copy operation. At least to me, read-only should allow copying FROM a table, but should not allow copying TO a table. Does that make sense?
