### ISSUE TITLE
Multiplication in select field list inhibts autocomplete 

### ISSUE THREAD

**Issue by mclaborn** [webyog/sqlyog-community#2268]
SQLyog Ultimate 13.1.7

A multiplication operator in the field list of a SELECT statement inhibits autocomplete for column names from a table alias following that multiplication operator. Given the query below, when I add a new field to the end of the select list, beginning with "h." the column name autocomplete does not display.  If I change the * to a comma, the autocomplete displays. 

SELECT b.`sku`, b.`name`, e.`hatch_date`, h.`eggset` * h.`percentyield` AS projected,
	h.`actualhatched`
	FROM hatch h, hatch_event e, breed b
	WHERE h.`hatcheventid` = e.`hatcheventid`
	AND h.`breedid` = b.`breedid`

**Comment by illfated** [comment]
(just to quote your SQL part, with a MarkDown code block and syntax highlighting)

```sql
SELECT b.`sku`, b.`name`, e.`hatch_date`, h.`eggset` * h.`percentyield` AS projected,
    h.`actualhatched`
  FROM hatch h, hatch_event e, breed b
  WHERE h.`hatcheventid` = e.`hatcheventid`
    AND h.`breedid` = b.`breedid`;
```

**Comment by sibwy** [comment]
You may remove the whitespace before "`h.percentyield AS projected`", (i.e., `SELECT b.sku, b.name, e.hatch_date, h.eggset *h.percentyield AS projected`,) and the autocomplete should work.

Also, in the future, please contact us by email at [ideramysqlsupport@idera.com](mailto:ideramysqlsupport@idera.com) about this. The way we use GitHub is strictly as an issue-tracker for known issues and not for support or discussions. This is necessary in order to keep the system manageable.
